import type { Severity } from '@cybermat/shared';

export interface SecretDetector {
  id: string;
  name: string;
  pattern: RegExp;
  valueGroup?: number;
  baseSeverity: Severity;
  frontendSeverity?: Severity;
  envFileSeverity?: Severity;
  cwe: string[];
  owasp: string[];
  tags: string[];
  impact: string;
  recommendation: string;
  /** Lower confidence for generic patterns prone to false positives */
  confidence?: 'high' | 'medium' | 'low';
  /** Require Shannon entropy check — useful for generic API key patterns */
  entropyRequired?: boolean;
  /** Minimum Shannon entropy for value to be considered real (default 3.5) */
  minEntropy?: number;
  /** Known false-positive patterns — matched values are downgraded to low confidence */
  falsePositivePatterns?: RegExp[];
  /** Variable name hints for context-aware detection */
  variableNameHints?: string[];
  /** Tag findings from example/test files with 'possible_test_fixture' but do not skip */
  allowInExampleFiles?: boolean;
}

export const SECRET_DETECTORS: SecretDetector[] = [
  // ─── Cloud ───────────────────────────────────────────────────────────────
  {
    id: 'secrets.aws-access-key-id',
    name: 'AWS Access Key ID',
    pattern: /(?:AWS_ACCESS_KEY_ID\s*[=:]\s*["']?|(["']))(AKIA[A-Z0-9]{16})\1?/,
    valueGroup: 2,
    baseSeverity: 'critical',
    cwe: ['CWE-798'],
    owasp: ['A04 Cryptographic Failures'],
    tags: ['aws', 'cloud', 'iam'],
    impact: 'Full AWS account access including EC2, S3, RDS, Lambda and billing.',
    recommendation: 'Rotate the AWS access key immediately in IAM. Use IAM roles instead of long-lived keys.',
    variableNameHints: ['AWS_ACCESS_KEY_ID', 'aws_access_key'],
    falsePositivePatterns: [/^AKIAIOSFODNN7EXAMPLE$/],
  },
  {
    id: 'secrets.aws-secret-access-key',
    name: 'AWS Secret Access Key',
    pattern: /AWS_SECRET_ACCESS_KEY\s*[=:]\s*["']?([A-Za-z0-9/+]{40})["']?/,
    valueGroup: 1,
    baseSeverity: 'critical',
    cwe: ['CWE-798'],
    owasp: ['A04 Cryptographic Failures'],
    tags: ['aws', 'cloud', 'iam'],
    impact: 'Full AWS API access. Paired with an access key this grants complete account control.',
    recommendation: 'Rotate immediately. Use AWS Secrets Manager or IAM roles for EC2/Lambda.',
  },
  {
    id: 'secrets.azure-client-secret',
    name: 'Azure Client Secret',
    pattern: /(?:AZURE_CLIENT_SECRET|AZURE_AD_CLIENT_SECRET)\s*[=:]\s*["']?([A-Za-z0-9~._\-]{34,40})["']?/,
    valueGroup: 1,
    baseSeverity: 'critical',
    cwe: ['CWE-798'],
    owasp: ['A04 Cryptographic Failures'],
    tags: ['azure', 'cloud', 'aad'],
    impact: 'Unauthorized access to Azure resources and Active Directory tenant.',
    recommendation: 'Rotate the client secret in Azure portal. Use Managed Identities where possible.',
  },
  {
    id: 'secrets.gcp-service-account-key',
    name: 'GCP / Firebase Service Account Key',
    pattern: /"type"\s*:\s*"service_account"/,
    baseSeverity: 'critical',
    cwe: ['CWE-798'],
    owasp: ['A04 Cryptographic Failures'],
    tags: ['gcp', 'firebase', 'cloud'],
    impact: 'Full GCP service account access. Can read/write all resources the account has permissions for.',
    recommendation: 'Revoke the key in GCP IAM console and rotate. Use Workload Identity Federation instead.',
  },
  {
    id: 'secrets.cloudflare-api-token',
    name: 'Cloudflare API Token',
    pattern: /(?:CLOUDFLARE_API_TOKEN|CF_API_TOKEN)\s*[=:]\s*["']?([A-Za-z0-9_-]{40})["']?/,
    valueGroup: 1,
    baseSeverity: 'high',
    cwe: ['CWE-798'],
    owasp: ['A04 Cryptographic Failures'],
    tags: ['cloudflare', 'cloud', 'dns'],
    impact: 'Unauthorized DNS changes, zone management, and Workers deployments.',
    recommendation: 'Rotate the token in Cloudflare dashboard. Scope tokens to minimum required permissions.',
  },

  // ─── Auth / Session ───────────────────────────────────────────────────────
  {
    id: 'secrets.clerk-secret-key',
    name: 'Clerk Secret Key',
    pattern: /CLERK_SECRET_KEY\s*[=:]\s*["']?(sk_(?:live|test)_[a-zA-Z0-9]{20,})["']?/,
    valueGroup: 1,
    baseSeverity: 'critical',
    frontendSeverity: 'critical',
    cwe: ['CWE-798', 'CWE-287'],
    owasp: ['A04 Cryptographic Failures', 'A07 Authentication Failures'],
    tags: ['clerk', 'auth', 'jwt'],
    impact: 'Full authentication system compromise. Token forgery and user impersonation.',
    recommendation: 'Rotate in Clerk dashboard immediately. Never expose in client code.',
  },
  {
    id: 'secrets.nextauth-secret',
    name: 'NextAuth / Auth.js Secret',
    pattern: /(?:NEXTAUTH_SECRET|AUTH_SECRET)\s*[=:]\s*["']?([^\s"'\n]{8,})["']?/,
    valueGroup: 1,
    baseSeverity: 'high',
    cwe: ['CWE-798', 'CWE-321'],
    owasp: ['A04 Cryptographic Failures', 'A07 Authentication Failures'],
    tags: ['nextauth', 'auth', 'session'],
    impact: 'Session and JWT forgery. Attackers can impersonate any user.',
    recommendation: 'Rotate the secret. Use a cryptographically random 32+ character value.',
  },
  {
    id: 'secrets.jwt-secret',
    name: 'JWT / Session Secret',
    pattern: /(?:JWT_SECRET|SESSION_SECRET|BETTER_AUTH_SECRET)\s*[=:]\s*["']?([^\s"'\n]{8,})["']?/,
    valueGroup: 1,
    baseSeverity: 'high',
    cwe: ['CWE-798', 'CWE-321'],
    owasp: ['A04 Cryptographic Failures', 'A07 Authentication Failures'],
    tags: ['jwt', 'auth', 'session'],
    impact: 'Token forgery allowing full account impersonation.',
    recommendation: 'Rotate the secret. Use openssl rand -base64 32 to generate a strong value.',
    entropyRequired: true,
    minEntropy: 3.5,
  },

  // ─── Databases ────────────────────────────────────────────────────────────
  {
    id: 'secrets.database-url',
    name: 'Database Connection String',
    pattern: /(?:DATABASE_URL|POSTGRES_URL|SUPABASE_DB_URL)\s*[=:]\s*["']?((?:postgresql|postgres):\/\/[^\s"'\n]+)["']?/,
    valueGroup: 1,
    baseSeverity: 'critical',
    cwe: ['CWE-798'],
    owasp: ['A04 Cryptographic Failures'],
    tags: ['database', 'postgres', 'credentials'],
    impact: 'Direct database access with credentials. Full data read/write/delete.',
    recommendation: 'Rotate database credentials. Never commit connection strings to source control.',
  },
  {
    id: 'secrets.mongodb-uri',
    name: 'MongoDB Connection URI',
    pattern: /(?:MONGODB_URI|MONGO_URL|MONGODB_URL)\s*[=:]\s*["']?(mongodb(?:\+srv)?:\/\/[^\s"'\n]+)["']?/,
    valueGroup: 1,
    baseSeverity: 'critical',
    cwe: ['CWE-798'],
    owasp: ['A04 Cryptographic Failures'],
    tags: ['database', 'mongodb', 'credentials'],
    impact: 'Direct MongoDB access with credentials enabling data exfiltration or destruction.',
    recommendation: 'Rotate credentials. Use MongoDB Atlas IP allowlisting and minimal-privilege roles.',
  },
  {
    id: 'secrets.redis-url',
    name: 'Redis Connection URL',
    pattern: /(?:REDIS_URL|REDIS_URI)\s*[=:]\s*["']?(rediss?:\/\/[^\s"'\n]+)["']?/,
    valueGroup: 1,
    baseSeverity: 'high',
    cwe: ['CWE-798'],
    owasp: ['A04 Cryptographic Failures'],
    tags: ['database', 'redis', 'cache'],
    impact: 'Unauthorized cache access, session theft, and queue manipulation.',
    recommendation: 'Rotate credentials. Use TLS (rediss://) and require authentication.',
  },
  {
    id: 'secrets.upstash-redis-token',
    name: 'Upstash Redis REST Token',
    pattern: /(?:UPSTASH_REDIS_REST_TOKEN|UPSTASH_TOKEN)\s*[=:]\s*["']?([A-Za-z0-9_\-]{20,})["']?/,
    valueGroup: 1,
    baseSeverity: 'high',
    cwe: ['CWE-798'],
    owasp: ['A04 Cryptographic Failures'],
    tags: ['upstash', 'redis', 'credentials'],
    impact: 'Full Upstash Redis access. Session data and cached secrets can be read or overwritten.',
    recommendation: 'Rotate the token in Upstash console. Store in server-only environment variables.',
  },

  // ─── Payments ─────────────────────────────────────────────────────────────
  {
    id: 'secrets.stripe-secret-key',
    name: 'Stripe Secret Key',
    pattern: /(?:STRIPE_SECRET_KEY\s*[=:]\s*["']?|["'])(sk_(?:live|test)_[a-zA-Z0-9]{24,})["']?/,
    valueGroup: 1,
    baseSeverity: 'critical',
    frontendSeverity: 'critical',
    envFileSeverity: 'high',
    cwe: ['CWE-798'],
    owasp: ['A04 Cryptographic Failures'],
    tags: ['stripe', 'payments', 'financial'],
    impact: 'Unauthorized payment processing, customer data access, and financial fraud.',
    recommendation: 'Rotate the Stripe secret key immediately. Use only in server-side environment variables.',
  },
  {
    id: 'secrets.stripe-webhook-secret',
    name: 'Stripe Webhook Secret',
    pattern: /STRIPE_WEBHOOK_SECRET\s*[=:]\s*["']?(whsec_[a-zA-Z0-9]+)["']?/,
    valueGroup: 1,
    baseSeverity: 'high',
    cwe: ['CWE-798'],
    owasp: ['A08 Software or Data Integrity Failures'],
    tags: ['stripe', 'webhook', 'payments'],
    impact: 'Attackers can forge Stripe webhook events to trigger unauthorized payment flows.',
    recommendation: 'Rotate the webhook signing secret in Stripe dashboard.',
  },
  {
    id: 'secrets.paypal-client-secret',
    name: 'PayPal Client Secret',
    pattern: /(?:PAYPAL_CLIENT_SECRET|PAYPAL_SECRET)\s*[=:]\s*["']?([A-Za-z0-9_\-]{20,})["']?/,
    valueGroup: 1,
    baseSeverity: 'critical',
    cwe: ['CWE-798'],
    owasp: ['A04 Cryptographic Failures'],
    tags: ['paypal', 'payments', 'financial'],
    impact: 'Unauthorized PayPal API access, payment fraud, and customer data exposure.',
    recommendation: 'Rotate the client secret in PayPal Developer Dashboard immediately.',
  },
  {
    id: 'secrets.lemon-squeezy-api-key',
    name: 'Lemon Squeezy API Key',
    pattern: /(?:LEMON_SQUEEZY_API_KEY|LEMONSQUEEZY_API_KEY)\s*[=:]\s*["']?([A-Za-z0-9_\-]{20,})["']?/,
    valueGroup: 1,
    baseSeverity: 'high',
    cwe: ['CWE-798'],
    owasp: ['A04 Cryptographic Failures'],
    tags: ['lemon-squeezy', 'payments'],
    impact: 'Unauthorized access to product catalog, subscriptions, and customer data.',
    recommendation: 'Rotate the API key in Lemon Squeezy dashboard. Store server-side only.',
  },

  // ─── AI Providers ─────────────────────────────────────────────────────────
  {
    id: 'secrets.openai-api-key',
    name: 'OpenAI API Key',
    pattern: /(?:OPENAI_API_KEY\s*[=:]\s*["']?|["'])(sk-(?:proj-)?[a-zA-Z0-9\-_]{32,})["']?/,
    valueGroup: 1,
    baseSeverity: 'high',
    frontendSeverity: 'critical',
    cwe: ['CWE-798'],
    owasp: ['A04 Cryptographic Failures'],
    tags: ['openai', 'ai', 'llm'],
    impact: 'Unauthorized API usage, unexpected billing, and data exposure via API calls.',
    recommendation: 'Rotate in OpenAI dashboard. Use a backend proxy; never call OpenAI directly from client code.',
    falsePositivePatterns: [/^sk-your[_-]/i, /^sk-example/i, /^sk-test-key/i],
  },
  {
    id: 'secrets.anthropic-api-key',
    name: 'Anthropic API Key',
    pattern: /(?:ANTHROPIC_API_KEY\s*[=:]\s*["']?|["'])(sk-ant-[a-zA-Z0-9\-_]{20,})["']?/,
    valueGroup: 1,
    baseSeverity: 'high',
    frontendSeverity: 'critical',
    cwe: ['CWE-798'],
    owasp: ['A04 Cryptographic Failures'],
    tags: ['anthropic', 'ai', 'llm'],
    impact: 'Unauthorized Anthropic API usage and unexpected billing.',
    recommendation: 'Rotate in Anthropic console. Store in server-only environment variables.',
    falsePositivePatterns: [/^sk-ant-your[_-]/i, /^sk-ant-example/i],
  },
  {
    id: 'secrets.google-api-key',
    name: 'Google / Gemini API Key',
    pattern: /(?:GOOGLE_API_KEY|GEMINI_API_KEY)\s*[=:]\s*["']?(AIza[a-zA-Z0-9_\-]{35})["']?/,
    valueGroup: 1,
    baseSeverity: 'high',
    frontendSeverity: 'critical',
    cwe: ['CWE-798'],
    owasp: ['A04 Cryptographic Failures'],
    tags: ['google', 'gemini', 'ai'],
    impact: 'Unauthorized Google API usage billed to your account, potential data leakage.',
    recommendation: 'Restrict the key in Google Cloud Console. Rotate and store server-side only.',
  },
  {
    id: 'secrets.mistral-api-key',
    name: 'Mistral API Key',
    pattern: /(?:MISTRAL_API_KEY)\s*[=:]\s*["']?([a-zA-Z0-9]{32,})["']?/,
    valueGroup: 1,
    baseSeverity: 'high',
    cwe: ['CWE-798'],
    owasp: ['A04 Cryptographic Failures'],
    tags: ['mistral', 'ai', 'llm'],
    impact: 'Unauthorized Mistral API usage and unexpected billing.',
    recommendation: 'Rotate in Mistral console. Store in server-only environment variables.',
  },
  {
    id: 'secrets.groq-api-key',
    name: 'Groq API Key',
    pattern: /(?:GROQ_API_KEY)\s*[=:]\s*["']?(gsk_[a-zA-Z0-9]{40,})["']?/,
    valueGroup: 1,
    baseSeverity: 'high',
    cwe: ['CWE-798'],
    owasp: ['A04 Cryptographic Failures'],
    tags: ['groq', 'ai', 'llm'],
    impact: 'Unauthorized Groq API usage and model access.',
    recommendation: 'Rotate in Groq console. Store in server-only environment variables.',
  },
  {
    id: 'secrets.elevenlabs-api-key',
    name: 'ElevenLabs API Key',
    pattern: /(?:ELEVENLABS_API_KEY|XI_API_KEY)\s*[=:]\s*["']?([a-f0-9]{32})["']?/,
    valueGroup: 1,
    baseSeverity: 'high',
    cwe: ['CWE-798'],
    owasp: ['A04 Cryptographic Failures'],
    tags: ['elevenlabs', 'ai', 'voice'],
    impact: 'Unauthorized voice synthesis usage and billing charges.',
    recommendation: 'Rotate in ElevenLabs dashboard. Never expose in client-side code.',
  },
  {
    id: 'secrets.huggingface-token',
    name: 'Hugging Face Token',
    pattern: /(?:HUGGINGFACE_TOKEN|HF_TOKEN|HUGGING_FACE_HUB_TOKEN)\s*[=:]\s*["']?(hf_[a-zA-Z0-9]{34,})["']?/,
    valueGroup: 1,
    baseSeverity: 'high',
    cwe: ['CWE-798'],
    owasp: ['A04 Cryptographic Failures'],
    tags: ['huggingface', 'ai', 'ml'],
    impact: 'Unauthorized model downloads, private model access, and inference API usage.',
    recommendation: 'Rotate in Hugging Face settings. Use read-only tokens scoped to required repos.',
  },
  {
    id: 'secrets.replicate-api-token',
    name: 'Replicate API Token',
    pattern: /(?:REPLICATE_API_TOKEN|REPLICATE_API_KEY)\s*[=:]\s*["']?(r8_[a-zA-Z0-9]{38,})["']?/,
    valueGroup: 1,
    baseSeverity: 'high',
    cwe: ['CWE-798'],
    owasp: ['A04 Cryptographic Failures'],
    tags: ['replicate', 'ai', 'ml'],
    impact: 'Unauthorized model predictions and billing charges.',
    recommendation: 'Rotate in Replicate account settings. Store server-side only.',
  },
  {
    id: 'secrets.together-api-key',
    name: 'Together AI API Key',
    pattern: /(?:TOGETHER_API_KEY|TOGETHER_AI_API_KEY)\s*[=:]\s*["']?([a-f0-9]{64})["']?/,
    valueGroup: 1,
    baseSeverity: 'high',
    cwe: ['CWE-798'],
    owasp: ['A04 Cryptographic Failures'],
    tags: ['together', 'ai', 'llm'],
    impact: 'Unauthorized LLM inference usage and billing charges.',
    recommendation: 'Rotate in Together AI dashboard. Store in server-only environment variables.',
  },

  // ─── Platforms ────────────────────────────────────────────────────────────
  {
    id: 'secrets.supabase-service-role-key',
    name: 'Supabase Service Role Key',
    pattern: /SUPABASE_SERVICE_ROLE_KEY\s*[=:]\s*["']?(eyJ[a-zA-Z0-9_-]{10,}\.[a-zA-Z0-9_-]+\.[a-zA-Z0-9_-]+)["']?/,
    valueGroup: 1,
    baseSeverity: 'critical',
    frontendSeverity: 'critical',
    envFileSeverity: 'high',
    cwe: ['CWE-798', 'CWE-287'],
    owasp: ['A04 Cryptographic Failures', 'A07 Authentication Failures'],
    tags: ['supabase', 'database', 'auth'],
    impact: 'Full database access bypassing Row Level Security. Anyone with this key can read, write, or delete all data.',
    recommendation: 'Rotate in Supabase dashboard. Never expose in client code. Use the anon key for frontend.',
  },
  {
    id: 'secrets.supabase-jwt-secret',
    name: 'Supabase JWT Secret',
    pattern: /SUPABASE_JWT_SECRET\s*[=:]\s*["']?([^\s"'\n]{20,})["']?/,
    valueGroup: 1,
    baseSeverity: 'critical',
    cwe: ['CWE-798', 'CWE-321'],
    owasp: ['A04 Cryptographic Failures', 'A07 Authentication Failures'],
    tags: ['supabase', 'jwt', 'auth'],
    impact: 'JWT forgery enabling impersonation of any Supabase user including service role.',
    recommendation: 'Rotate the JWT secret in Supabase project settings.',
  },
  {
    id: 'secrets.firebase-private-key',
    name: 'Firebase / GCP Service Account Private Key',
    pattern: /(?:FIREBASE_PRIVATE_KEY|GOOGLE_PRIVATE_KEY)\s*[=:]\s*["']?(-----BEGIN[^"']+)["']?/,
    valueGroup: 1,
    baseSeverity: 'critical',
    cwe: ['CWE-798'],
    owasp: ['A04 Cryptographic Failures'],
    tags: ['firebase', 'gcp', 'private-key'],
    impact: 'Full Firebase Admin SDK access. Can read/write all Firestore data and bypass Security Rules.',
    recommendation: 'Revoke the service account key in GCP console and rotate immediately.',
  },
  {
    id: 'secrets.firebase-client-email',
    name: 'Firebase Service Account Email',
    pattern: /(?:FIREBASE_CLIENT_EMAIL|GOOGLE_CLIENT_EMAIL)\s*[=:]\s*["']?([a-zA-Z0-9._%+\-]+@[a-zA-Z0-9.\-]+\.gserviceaccount\.com)["']?/,
    valueGroup: 1,
    baseSeverity: 'medium',
    cwe: ['CWE-200'],
    owasp: ['A02 Security Misconfiguration'],
    tags: ['firebase', 'gcp', 'service-account'],
    impact: 'Service account identity exposed. Combined with private key grants full admin access.',
    recommendation: 'Treat service account emails as sensitive. Avoid committing to source control.',
  },
  {
    id: 'secrets.vercel-token',
    name: 'Vercel API Token',
    pattern: /(?:VERCEL_TOKEN|VERCEL_ACCESS_TOKEN)\s*[=:]\s*["']?([a-zA-Z0-9]{24,})["']?/,
    valueGroup: 1,
    baseSeverity: 'high',
    cwe: ['CWE-798'],
    owasp: ['A04 Cryptographic Failures'],
    tags: ['vercel', 'deployment', 'ci-cd'],
    impact: 'Unauthorized deployments, environment variable access, and project deletion.',
    recommendation: 'Rotate in Vercel account settings. Scope tokens to specific teams/projects.',
  },
  {
    id: 'secrets.netlify-auth-token',
    name: 'Netlify Auth Token',
    pattern: /(?:NETLIFY_AUTH_TOKEN|NETLIFY_TOKEN)\s*[=:]\s*["']?([a-zA-Z0-9_\-]{20,})["']?/,
    valueGroup: 1,
    baseSeverity: 'high',
    cwe: ['CWE-798'],
    owasp: ['A04 Cryptographic Failures'],
    tags: ['netlify', 'deployment', 'ci-cd'],
    impact: 'Unauthorized site deployments, environment variable access, and DNS changes.',
    recommendation: 'Rotate in Netlify account settings.',
  },

  // ─── Communication ────────────────────────────────────────────────────────
  {
    id: 'secrets.resend-api-key',
    name: 'Resend API Key',
    pattern: /(?:RESEND_API_KEY)\s*[=:]\s*["']?(re_[a-zA-Z0-9_]{20,})["']?/,
    valueGroup: 1,
    baseSeverity: 'high',
    cwe: ['CWE-798'],
    owasp: ['A04 Cryptographic Failures'],
    tags: ['resend', 'email', 'comms'],
    impact: 'Unauthorized email sending, phishing campaigns, and spam from your domain.',
    recommendation: 'Rotate the API key in Resend dashboard. Store server-side only.',
  },
  {
    id: 'secrets.sendgrid-api-key',
    name: 'SendGrid API Key',
    pattern: /(?:SENDGRID_API_KEY)\s*[=:]\s*["']?(SG\.[a-zA-Z0-9_\-]{22}\.[a-zA-Z0-9_\-]{43})["']?/,
    valueGroup: 1,
    baseSeverity: 'high',
    cwe: ['CWE-798'],
    owasp: ['A04 Cryptographic Failures'],
    tags: ['sendgrid', 'email', 'comms'],
    impact: 'Unauthorized email sending from your domain, phishing, and account lockout.',
    recommendation: 'Rotate the API key in SendGrid settings. Restrict key permissions.',
  },
  {
    id: 'secrets.mailgun-api-key',
    name: 'Mailgun API Key',
    pattern: /(?:MAILGUN_API_KEY)\s*[=:]\s*["']?(key-[a-f0-9]{32})["']?/,
    valueGroup: 1,
    baseSeverity: 'high',
    cwe: ['CWE-798'],
    owasp: ['A04 Cryptographic Failures'],
    tags: ['mailgun', 'email', 'comms'],
    impact: 'Unauthorized email sending from your Mailgun domain.',
    recommendation: 'Rotate in Mailgun settings. Use domain-specific keys with minimal permissions.',
  },
  {
    id: 'secrets.twilio-auth-token',
    name: 'Twilio Auth Token',
    pattern: /(?:TWILIO_AUTH_TOKEN)\s*[=:]\s*["']?([a-f0-9]{32})["']?/,
    valueGroup: 1,
    baseSeverity: 'high',
    cwe: ['CWE-798'],
    owasp: ['A04 Cryptographic Failures'],
    tags: ['twilio', 'sms', 'comms'],
    impact: 'Unauthorized SMS/voice calls billed to your account, phone number takeover.',
    recommendation: 'Rotate in Twilio console. Use API keys instead of the master auth token.',
  },
  {
    id: 'secrets.slack-bot-token',
    name: 'Slack Bot Token',
    pattern: /(?:SLACK_BOT_TOKEN|SLACK_TOKEN)\s*[=:]\s*["']?(xox[bpars]-[a-zA-Z0-9\-]+)["']?/,
    valueGroup: 1,
    baseSeverity: 'high',
    cwe: ['CWE-798'],
    owasp: ['A04 Cryptographic Failures'],
    tags: ['slack', 'comms', 'workspace'],
    impact: 'Unauthorized Slack workspace access, message reading, and impersonation.',
    recommendation: 'Revoke in Slack app settings. Rotate and store server-side only.',
  },
  {
    id: 'secrets.discord-webhook-url',
    name: 'Discord Webhook URL',
    pattern: /(?:DISCORD_WEBHOOK_URL|discord\.com\/api\/webhooks\/)\s*[=:"\s]*(https:\/\/discord(?:app)?\.com\/api\/webhooks\/[0-9]+\/[a-zA-Z0-9_\-]+)/,
    valueGroup: 1,
    baseSeverity: 'medium',
    cwe: ['CWE-798'],
    owasp: ['A04 Cryptographic Failures'],
    tags: ['discord', 'webhook', 'comms'],
    impact: 'Anyone can post messages to the channel. Can be used for spam or to leak alert data.',
    recommendation: 'Reset the webhook in Discord channel settings.',
  },
  {
    id: 'secrets.telegram-bot-token',
    name: 'Telegram Bot Token',
    pattern: /(?:TELEGRAM_BOT_TOKEN|BOT_TOKEN)\s*[=:]\s*["']?([0-9]{8,10}:[a-zA-Z0-9_\-]{35})["']?/,
    valueGroup: 1,
    baseSeverity: 'high',
    cwe: ['CWE-798'],
    owasp: ['A04 Cryptographic Failures'],
    tags: ['telegram', 'bot', 'comms'],
    impact: 'Full bot control: read messages, send messages, impersonate the bot.',
    recommendation: 'Revoke via @BotFather /revoke command and issue a new token.',
  },

  // ─── Monitoring ───────────────────────────────────────────────────────────
  {
    id: 'secrets.sentry-auth-token',
    name: 'Sentry Auth Token',
    pattern: /(?:SENTRY_AUTH_TOKEN)\s*[=:]\s*["']?([a-f0-9]{64})["']?/,
    valueGroup: 1,
    baseSeverity: 'high',
    cwe: ['CWE-798'],
    owasp: ['A04 Cryptographic Failures'],
    tags: ['sentry', 'monitoring', 'error-tracking'],
    impact: 'Unauthorized access to Sentry projects, error data, and source maps.',
    recommendation: 'Rotate in Sentry API token settings. Use fine-grained scopes.',
  },
  {
    id: 'secrets.sentry-dsn',
    name: 'Sentry DSN',
    pattern: /SENTRY_DSN\s*[=:]\s*["']?(https:\/\/[a-f0-9]+@o[0-9]+\.ingest\.sentry\.io\/[0-9]+)["']?/,
    valueGroup: 1,
    baseSeverity: 'info',
    cwe: ['CWE-200'],
    owasp: ['A02 Security Misconfiguration'],
    tags: ['sentry', 'monitoring', 'public'],
    impact: 'Public Sentry DSN exposes project info and allows event submission. Low impact unless combined with auth tokens.',
    recommendation: 'Sentry DSN in frontend code is common and intended. Ensure no auth tokens are also exposed.',
  },
  {
    id: 'secrets.posthog-api-key',
    name: 'PostHog API Key',
    pattern: /(?:POSTHOG_API_KEY|POSTHOG_KEY)\s*[=:]\s*["']?(phc_[a-zA-Z0-9]{39,})["']?/,
    valueGroup: 1,
    baseSeverity: 'medium',
    cwe: ['CWE-798'],
    owasp: ['A04 Cryptographic Failures'],
    tags: ['posthog', 'analytics', 'monitoring'],
    impact: 'Unauthorized analytics data access and event injection.',
    recommendation: 'PostHog project API keys are semi-public for ingestion. Protect personal API keys only.',
  },
  {
    id: 'secrets.datadog-api-key',
    name: 'Datadog API Key',
    pattern: /(?:DATADOG_API_KEY|DD_API_KEY)\s*[=:]\s*["']?([a-f0-9]{32})["']?/,
    valueGroup: 1,
    baseSeverity: 'high',
    cwe: ['CWE-798'],
    owasp: ['A04 Cryptographic Failures'],
    tags: ['datadog', 'monitoring', 'observability'],
    impact: 'Unauthorized metric ingestion, log access, and infrastructure visibility.',
    recommendation: 'Rotate in Datadog organization settings. Store server-side only.',
  },
  {
    id: 'secrets.new-relic-license-key',
    name: 'New Relic License Key',
    pattern: /(?:NEW_RELIC_LICENSE_KEY|NEWRELIC_LICENSE_KEY)\s*[=:]\s*["']?([A-Za-z0-9]{40})["']?/,
    valueGroup: 1,
    baseSeverity: 'high',
    cwe: ['CWE-798'],
    owasp: ['A04 Cryptographic Failures'],
    tags: ['newrelic', 'monitoring', 'observability'],
    impact: 'Unauthorized metric and log ingestion, APM data access.',
    recommendation: 'Rotate in New Relic account settings.',
  },

  // ─── Dev Platforms ────────────────────────────────────────────────────────
  {
    id: 'secrets.github-token',
    name: 'GitHub Personal Access Token',
    pattern: /(?:GITHUB_TOKEN|GITHUB_PAT|GH_TOKEN)\s*[=:]\s*["']?((?:ghp|ghs|gho|ghu|github_pat)_[a-zA-Z0-9_]+)["']?/,
    valueGroup: 1,
    baseSeverity: 'high',
    cwe: ['CWE-798'],
    owasp: ['A04 Cryptographic Failures'],
    tags: ['github', 'ci-cd', 'vcs'],
    impact: 'Unauthorized access to GitHub repos, CI/CD pipelines, and organization secrets.',
    recommendation: 'Revoke immediately in GitHub settings. Use fine-grained PATs with minimal permissions.',
  },
  {
    id: 'secrets.gitlab-token',
    name: 'GitLab Token',
    pattern: /(?:GITLAB_TOKEN|GITLAB_PAT|CI_JOB_TOKEN)\s*[=:]\s*["']?(glpat-[a-zA-Z0-9_\-]{20,})["']?/,
    valueGroup: 1,
    baseSeverity: 'high',
    cwe: ['CWE-798'],
    owasp: ['A04 Cryptographic Failures'],
    tags: ['gitlab', 'ci-cd', 'vcs'],
    impact: 'Unauthorized access to GitLab repositories and CI/CD pipelines.',
    recommendation: 'Revoke in GitLab user settings. Use project-scoped access tokens where possible.',
  },
  {
    id: 'secrets.npm-token',
    name: 'npm Publish Token',
    pattern: /(?:NPM_TOKEN|NPM_AUTH_TOKEN)\s*[=:]\s*["']?(npm_[a-zA-Z0-9]{36})["']?/,
    valueGroup: 1,
    baseSeverity: 'high',
    cwe: ['CWE-798'],
    owasp: ['A04 Cryptographic Failures', 'A03 Software Supply Chain Failures'],
    tags: ['npm', 'registry', 'supply-chain'],
    impact: 'Unauthorized package publishing enabling supply chain attacks.',
    recommendation: 'Revoke in npm account settings. Use automation tokens scoped to specific packages.',
  },
  {
    id: 'secrets.dockerhub-token',
    name: 'Docker Hub Token',
    pattern: /(?:DOCKERHUB_TOKEN|DOCKER_HUB_TOKEN|DOCKER_PASSWORD)\s*[=:]\s*["']?([a-zA-Z0-9_\-]{20,})["']?/,
    valueGroup: 1,
    baseSeverity: 'high',
    cwe: ['CWE-798'],
    owasp: ['A04 Cryptographic Failures'],
    tags: ['docker', 'registry', 'containers'],
    impact: 'Unauthorized image pushes enabling supply chain attacks on container images.',
    recommendation: 'Rotate in Docker Hub access token settings. Scope to specific repos.',
  },

  // ─── Private Keys ─────────────────────────────────────────────────────────
  {
    id: 'secrets.rsa-private-key',
    name: 'RSA Private Key',
    pattern: /-----BEGIN RSA PRIVATE KEY-----/,
    baseSeverity: 'critical',
    cwe: ['CWE-321'],
    owasp: ['A04 Cryptographic Failures'],
    tags: ['private-key', 'rsa', 'cryptography'],
    impact: 'RSA private key exposed. Attackers can decrypt communications or impersonate the key owner.',
    recommendation: 'Remove from source. Revoke and rotate the key pair immediately.',
  },
  {
    id: 'secrets.ec-private-key',
    name: 'EC Private Key',
    pattern: /-----BEGIN EC PRIVATE KEY-----/,
    baseSeverity: 'critical',
    cwe: ['CWE-321'],
    owasp: ['A04 Cryptographic Failures'],
    tags: ['private-key', 'ec', 'cryptography'],
    impact: 'EC private key exposed. Attackers can forge signatures and decrypt ECDH-encrypted data.',
    recommendation: 'Remove from source. Revoke and rotate the key pair immediately.',
  },
  {
    id: 'secrets.openssh-private-key',
    name: 'OpenSSH Private Key',
    pattern: /-----BEGIN OPENSSH PRIVATE KEY-----/,
    baseSeverity: 'critical',
    cwe: ['CWE-321'],
    owasp: ['A04 Cryptographic Failures'],
    tags: ['private-key', 'ssh', 'cryptography'],
    impact: 'SSH private key exposed. Attackers can authenticate to any server where the public key is authorized.',
    recommendation: 'Remove from source. Remove from authorized_keys on all servers and rotate.',
  },
  {
    id: 'secrets.pgp-private-key',
    name: 'PGP Private Key',
    pattern: /-----BEGIN PGP PRIVATE KEY BLOCK-----/,
    baseSeverity: 'critical',
    cwe: ['CWE-321'],
    owasp: ['A04 Cryptographic Failures'],
    tags: ['private-key', 'pgp', 'cryptography'],
    impact: 'PGP private key exposed. Attackers can decrypt PGP-encrypted messages.',
    recommendation: 'Remove from source. Revoke and publish a new key immediately.',
  },
  {
    id: 'secrets.generic-private-key',
    name: 'Private Key Material',
    pattern: /-----BEGIN\s+(?:ENCRYPTED\s+)?PRIVATE KEY-----/,
    baseSeverity: 'critical',
    cwe: ['CWE-321'],
    owasp: ['A04 Cryptographic Failures'],
    tags: ['private-key', 'pem', 'cryptography'],
    impact: 'Cryptographic private key material exposed. Attackers can impersonate servers or decrypt data.',
    recommendation: 'Remove from source control. Revoke and rotate the key pair.',
  },

  // ─── Connection Strings ───────────────────────────────────────────────────
  {
    id: 'secrets.mysql-connection-string',
    name: 'MySQL Connection String',
    pattern: /mysql(?:2)?:\/\/[^:]+:[^@\s"'\n]{4,}@[^\s"'\n]+/,
    baseSeverity: 'critical',
    cwe: ['CWE-798'],
    owasp: ['A04 Cryptographic Failures'],
    tags: ['database', 'mysql', 'credentials'],
    impact: 'Direct MySQL access with credentials embedded in the connection string.',
    recommendation: 'Rotate database credentials. Use a secrets manager or environment variables without committing.',
  },
  {
    id: 'secrets.mongodb-connection-string',
    name: 'MongoDB Connection String with Credentials',
    pattern: /mongodb(?:\+srv)?:\/\/[^:]+:[^@\s"'\n]{4,}@[^\s"'\n]+/,
    baseSeverity: 'critical',
    cwe: ['CWE-798'],
    owasp: ['A04 Cryptographic Failures'],
    tags: ['database', 'mongodb', 'credentials'],
    impact: 'Direct MongoDB access with embedded credentials.',
    recommendation: 'Rotate credentials. Use environment variables and never commit connection strings.',
  },
  {
    id: 'secrets.redis-connection-string',
    name: 'Redis Connection String with Password',
    pattern: /rediss?:\/\/[^:@\s]+:[^@\s"'\n]{4,}@[^\s"'\n]+/,
    baseSeverity: 'high',
    cwe: ['CWE-798'],
    owasp: ['A04 Cryptographic Failures'],
    tags: ['database', 'redis', 'credentials'],
    impact: 'Redis access with embedded password. Session data and cached secrets can be stolen.',
    recommendation: 'Rotate the Redis password. Store connection string in environment variables only.',
  },
  {
    id: 'secrets.amqp-connection-string',
    name: 'AMQP / RabbitMQ Connection String',
    pattern: /amqps?:\/\/[^:]+:[^@\s"'\n]{4,}@[^\s"'\n]+/,
    baseSeverity: 'high',
    cwe: ['CWE-798'],
    owasp: ['A04 Cryptographic Failures'],
    tags: ['queue', 'rabbitmq', 'credentials'],
    impact: 'Message queue access. Attackers can read, inject, or consume sensitive messages.',
    recommendation: 'Rotate credentials. Store connection string in environment variables only.',
  },
  {
    id: 'secrets.smtp-connection-string',
    name: 'SMTP Connection String with Credentials',
    pattern: /smtps?:\/\/[^:]+:[^@\s"'\n]{4,}@[^\s"'\n]+/,
    baseSeverity: 'high',
    cwe: ['CWE-798'],
    owasp: ['A04 Cryptographic Failures'],
    tags: ['email', 'smtp', 'credentials'],
    impact: 'SMTP relay access. Attackers can send email from your domain.',
    recommendation: 'Rotate SMTP credentials. Use an email API service with API keys instead.',
  },
];
