import type { RulePack } from '@cybermat/shared';

export const aiSecurityPack: RulePack = {
  id: 'ai-security',
  name: 'AI-Specific Security',
  description: 'Detects insecure patterns in AI-assisted and AI-agent code including prompt injection, unsafe LLM output rendering, and missing approval gates',
  rules: [
    {
      id: 'ai.llm-output-html-sink',
      name: 'LLM Output Rendered as Raw HTML',
      description: 'AI/LLM output variable flows directly into an HTML sink (dangerouslySetInnerHTML, innerHTML) without sanitization',
      engine: 'ai',
      category: 'AI Security',
      severity: 'high',
      confidence: 'high',
      owasp2025: ['A05 Injection', 'A06 Insecure Design'],
      cwe: ['CWE-79', 'CWE-116'],
      asvs: ['ASVS 5.2.1'],
      wstg: ['WSTG-INPV-01'],
      tags: ['llm', 'xss', 'prompt-injection', 'ai'],
      enabledByDefault: true,
      safeForCI: true,
      requiresRuntime: false,
      requiresAuth: false,
      falsePositiveNotes: 'May fire on AI variable names used for non-HTML purposes. Verify the sink type.',
      remediation: 'Always sanitize AI-generated HTML with DOMPurify before rendering. Use a content allowlist for LLM output.',
      insecureExample: 'const aiResponse = await openai.complete(prompt);\n<div dangerouslySetInnerHTML={{ __html: aiResponse }} />',
      saferExample: 'import DOMPurify from "dompurify";\n<div dangerouslySetInnerHTML={{ __html: DOMPurify.sanitize(aiResponse, { ALLOWED_TAGS: ["b","i","p"] }) }} />',
    },
    {
      id: 'ai.llm-output-critical-sink',
      name: 'LLM Output Flowing to Dangerous Operation',
      description: 'LLM output variable flows into exec/SQL/fetch/delete operation without sanitization — prompt injection can cause catastrophic actions',
      engine: 'ai',
      category: 'AI Security',
      severity: 'critical',
      confidence: 'medium',
      owasp2025: ['A05 Injection', 'A06 Insecure Design'],
      cwe: ['CWE-78', 'CWE-89', 'CWE-918'],
      asvs: ['ASVS 5.3.8'],
      wstg: ['WSTG-INPV-12'],
      tags: ['llm', 'prompt-injection', 'rce', 'ai', 'critical'],
      enabledByDefault: true,
      safeForCI: true,
      requiresRuntime: false,
      requiresAuth: false,
      remediation: 'Never pass LLM output directly to command execution, SQL, or HTTP requests. Validate with a strict allowlist of permitted operations.',
      insecureExample: 'const completion = await claude.complete(userPrompt);\nexec(completion); // prompt injection = RCE',
      saferExample: '// Use structured output with enum validation\nconst { tool, args } = JSON.parse(completion);\nconst ALLOWED_TOOLS = ["search", "summarize"];\nif (!ALLOWED_TOOLS.includes(tool)) throw new Error("Disallowed tool");',
    },
    {
      id: 'ai.tool-call-no-approval',
      name: 'AI Tool Call Executing Dangerous Operation Without Approval',
      description: 'AI agent executes a destructive operation (exec, delete, file write, email) without a human approval check in surrounding code',
      engine: 'ai',
      category: 'AI Security',
      severity: 'critical',
      confidence: 'medium',
      owasp2025: ['A06 Insecure Design', 'A08 Software or Data Integrity Failures'],
      cwe: ['CWE-284', 'CWE-862'],
      asvs: ['ASVS 4.2.2'],
      wstg: ['WSTG-BUSL-07'],
      tags: ['ai-agent', 'tool-use', 'prompt-injection', 'human-in-loop'],
      enabledByDefault: true,
      safeForCI: true,
      requiresRuntime: false,
      requiresAuth: false,
      falsePositiveNotes: 'Medium confidence — approval keywords may appear in variable names rather than actual approval logic. Review carefully.',
      remediation: 'Require human approval for destructive tool calls. Implement an allowlist of permitted operations and require explicit confirmation.',
      insecureExample: 'if (toolCall.name === "delete_file") {\n  fs.unlink(toolCall.args.path, cb); // no confirmation\n}',
      saferExample: 'if (toolCall.name === "delete_file") {\n  const approved = await requireUserApproval(`Delete ${toolCall.args.path}?`);\n  if (!approved) return { error: "Operation cancelled" };\n  fs.unlink(toolCall.args.path, cb);\n}',
    },
    {
      id: 'ai.user-input-in-system-prompt',
      name: 'User Input Concatenated into AI System Prompt',
      description: 'User-controlled content appears to be concatenated into the AI system/developer prompt, enabling prompt injection',
      engine: 'ai',
      category: 'AI Security',
      severity: 'high',
      confidence: 'medium',
      owasp2025: ['A05 Injection', 'A06 Insecure Design'],
      cwe: ['CWE-77'],
      asvs: ['ASVS 5.2.4'],
      wstg: ['WSTG-INPV-11'],
      tags: ['prompt-injection', 'llm', 'ai'],
      enabledByDefault: true,
      safeForCI: true,
      requiresRuntime: false,
      requiresAuth: false,
      falsePositiveNotes: 'Medium confidence based on variable naming patterns. May fire on coincidental variable name similarities.',
      remediation: 'Keep system prompts static. Use structured message roles — never concatenate user input into system instructions.',
      insecureExample: 'const systemPrompt = "You are a helpful assistant. User context: " + userMessage;',
      saferExample: '// Keep system prompt static; put user input only in user role:\n[\n  { role: "system", content: "You are a helpful assistant." },\n  { role: "user", content: userMessage }, // user input here only\n]',
    },
    {
      id: 'ai.rag-injection-risk',
      name: 'RAG Documents Mixed into AI System Instructions',
      description: 'Retrieved documents appear to be concatenated into system-level AI instructions, enabling indirect prompt injection',
      engine: 'ai',
      category: 'AI Security',
      severity: 'medium',
      confidence: 'low',
      owasp2025: ['A05 Injection'],
      cwe: ['CWE-77'],
      asvs: ['ASVS 5.2.4'],
      wstg: ['WSTG-INPV-11'],
      tags: ['rag', 'prompt-injection', 'llm', 'ai'],
      enabledByDefault: true,
      safeForCI: true,
      requiresRuntime: false,
      requiresAuth: false,
      falsePositiveNotes: 'Low confidence — pattern matching on variable names may produce false positives. Review the actual message structure.',
      remediation: 'Separate system instructions from retrieved context. Use a distinct "tool" or "assistant" message role for retrieved documents.',
      insecureExample: 'const systemPrompt = `Instructions: ${baseInstructions}\\nContext: ${documents.join("\\n")}`;',
      saferExample: '[\n  { role: "system", content: baseInstructions },\n  { role: "user", content: `Context documents:\\n${documents.join("\\n")}\\n\\nQuestion: ${question}` },\n]',
    },
  ],
};
