import type { RulePack } from '@cybermat/shared';

export const authPack: RulePack = {
  id: 'auth',
  name: 'Authentication & Access Control',
  description: 'Detects missing auth guards, broken access control, insecure webhook handling, IDOR, and framework-specific auth issues',
  rules: [
    {
      id: 'auth.missing-middleware',
      name: 'Missing Next.js Middleware',
      description: 'No middleware.ts found in Next.js project — authentication is not enforced at the routing layer, making it easy to miss protecting routes',
      engine: 'static',
      category: 'Authentication',
      severity: 'medium',
      confidence: 'medium',
      owasp2025: ['A01 Broken Access Control', 'A07 Authentication Failures'],
      cwe: ['CWE-284'],
      asvs: ['ASVS 1.4.1'],
      wstg: ['WSTG-ATHN-01'],
      tags: ['nextjs', 'middleware', 'auth'],
      enabledByDefault: true,
      safeForCI: true,
      requiresRuntime: false,
      requiresAuth: false,
      falsePositiveNotes: 'Some Next.js apps enforce auth per-route rather than in middleware. Verify your auth strategy.',
      remediation: 'Add middleware.ts to enforce authentication at the edge. Use Clerk, NextAuth, or custom JWT validation.',
      insecureExample: '// No middleware.ts — every route is public by default',
      saferExample: '// middleware.ts\nimport { clerkMiddleware, createRouteMatcher } from "@clerk/nextjs/server";\nconst isPublic = createRouteMatcher(["/", "/sign-in"]);\nexport default clerkMiddleware((auth, req) => { if (!isPublic(req)) auth().protect(); });',
    },
    {
      id: 'auth.admin-route-no-auth',
      name: 'Admin Route Without Authentication Check',
      description: 'An API route under /admin or /api/admin has no detectable authentication guard, potentially allowing unauthenticated access',
      engine: 'static',
      category: 'Authentication',
      severity: 'critical',
      confidence: 'medium',
      owasp2025: ['A01 Broken Access Control', 'A07 Authentication Failures'],
      cwe: ['CWE-284', 'CWE-306'],
      asvs: ['ASVS 1.4.2'],
      wstg: ['WSTG-ATHN-01'],
      tags: ['admin', 'auth', 'access-control'],
      enabledByDefault: true,
      safeForCI: true,
      requiresRuntime: false,
      requiresAuth: false,
      falsePositiveNotes: 'Auth may be enforced at the middleware layer. Verify your global auth strategy before suppressing.',
      remediation: 'Add authentication and role/admin check at the start of every admin route handler.',
      insecureExample: 'export async function GET() {\n  return Response.json(await db.users.findAll()); // no auth\n}',
      saferExample: 'export async function GET() {\n  const { userId } = await auth();\n  if (!userId) return new Response("Unauthorized", { status: 401 });\n  const user = await db.users.findById(userId);\n  if (user.role !== "admin") return new Response("Forbidden", { status: 403 });\n  return Response.json(await db.users.findAll());\n}',
    },
    {
      id: 'auth.admin-route-no-role-check',
      name: 'Admin Route Missing Role Check',
      description: 'Admin route is authenticated but no role/admin check is present — any authenticated user may reach admin functionality',
      engine: 'static',
      category: 'Authentication',
      severity: 'high',
      confidence: 'low',
      owasp2025: ['A01 Broken Access Control'],
      cwe: ['CWE-284', 'CWE-285'],
      asvs: ['ASVS 4.1.3'],
      wstg: ['WSTG-ATHZ-02'],
      tags: ['admin', 'rbac', 'access-control'],
      enabledByDefault: true,
      safeForCI: true,
      requiresRuntime: false,
      requiresAuth: false,
      falsePositiveNotes: 'Role check may use a different pattern not recognized. Review carefully before suppressing.',
      remediation: 'Add a role check after authentication: verify the user has an admin role before proceeding.',
      insecureExample: 'const { userId } = await auth(); // authenticated but no role check\nreturn Response.json(await db.users.findAll());',
      saferExample: 'const { userId } = await auth();\nconst user = await db.users.findById(userId);\nif (user.role !== "admin") return new Response("Forbidden", { status: 403 });',
    },
    {
      id: 'auth.protected-route-no-auth',
      name: 'Protected-Looking Route Without Authentication',
      description: 'Route path contains a sensitive keyword (dashboard, settings, billing, etc.) but no auth guard was detected',
      engine: 'static',
      category: 'Authentication',
      severity: 'high',
      confidence: 'low',
      owasp2025: ['A01 Broken Access Control', 'A07 Authentication Failures'],
      cwe: ['CWE-284'],
      asvs: ['ASVS 1.4.1'],
      wstg: ['WSTG-ATHN-01'],
      tags: ['auth', 'access-control'],
      enabledByDefault: true,
      safeForCI: true,
      requiresRuntime: false,
      requiresAuth: false,
      falsePositiveNotes: 'Low confidence — auth may be enforced in middleware. Verify before suppressing.',
      remediation: 'Verify authentication is enforced. Add an explicit auth check at the top of the route handler.',
      insecureExample: '// app/api/billing/route.ts — no auth check\nexport async function POST(req: Request) {\n  const body = await req.json();\n  return createSubscription(body.planId);\n}',
      saferExample: 'const { userId } = await auth();\nif (!userId) return new Response("Unauthorized", { status: 401 });',
    },
    {
      id: 'auth.webhook-missing-signature',
      name: 'Webhook Route Missing Signature Verification',
      description: 'Webhook route processes events without verifying the provider\'s cryptographic signature — anyone can forge events',
      engine: 'static',
      category: 'Authentication',
      severity: 'high',
      confidence: 'medium',
      owasp2025: ['A08 Software or Data Integrity Failures'],
      cwe: ['CWE-347'],
      asvs: ['ASVS 10.3.2'],
      wstg: ['WSTG-BUSL-07'],
      tags: ['webhook', 'auth', 'integrity'],
      enabledByDefault: true,
      safeForCI: true,
      requiresRuntime: false,
      requiresAuth: false,
      remediation: 'Verify webhook signatures using the provider SDK: stripe.webhooks.constructEvent(), Svix, or x-hub-signature for GitHub/GitLab.',
      insecureExample: 'export async function POST(req: Request) {\n  const body = await req.json(); // no signature check\n  await fulfillOrder(body.orderId);\n}',
      saferExample: 'const sig = req.headers.get("stripe-signature")!;\nconst event = stripe.webhooks.constructEvent(rawBody, sig, process.env.STRIPE_WEBHOOK_SECRET!);',
    },
    {
      id: 'auth.stripe-payment-success-query-param',
      name: 'Payment Success Logic Trusting Query Parameters',
      description: 'Payment success/status is read from a query parameter — attackers can craft a ?success=true URL to bypass payment',
      engine: 'static',
      category: 'Authentication',
      severity: 'high',
      confidence: 'medium',
      owasp2025: ['A08 Software or Data Integrity Failures'],
      cwe: ['CWE-807'],
      asvs: ['ASVS 10.3.1'],
      wstg: ['WSTG-BUSL-04'],
      tags: ['stripe', 'payment', 'integrity'],
      enabledByDefault: true,
      safeForCI: true,
      requiresRuntime: false,
      requiresAuth: false,
      remediation: 'Verify payment status via Stripe webhook events or server-side Stripe API, never from client query params.',
      insecureExample: 'const success = searchParams.get("success"); // attacker can set ?success=true',
      saferExample: '// Verify via webhook event or server-side API call\nconst session = await stripe.checkout.sessions.retrieve(sessionId);\nif (session.payment_status !== "paid") return error();',
    },
    {
      id: 'auth.clerk-api-route-no-auth',
      name: 'Clerk API Route Missing auth() Call',
      description: 'Clerk is detected in the project but this API route has no auth() or currentUser() call — may be publicly accessible',
      engine: 'static',
      category: 'Authentication',
      severity: 'high',
      confidence: 'low',
      owasp2025: ['A01 Broken Access Control', 'A07 Authentication Failures'],
      cwe: ['CWE-306'],
      asvs: ['ASVS 1.4.1'],
      wstg: ['WSTG-ATHN-01'],
      tags: ['clerk', 'auth', 'nextjs'],
      enabledByDefault: true,
      safeForCI: true,
      requiresRuntime: false,
      requiresAuth: false,
      falsePositiveNotes: 'Low confidence — route may be intentionally public (e.g., public API endpoint). Verify intent.',
      remediation: 'Call auth() or currentUser() from @clerk/nextjs at the top of every protected API route.',
      insecureExample: 'export async function GET() {\n  return Response.json(await db.profile.findAll()); // Clerk project but no auth()\n}',
      saferExample: 'import { auth } from "@clerk/nextjs/server";\nexport async function GET() {\n  const { userId } = auth();\n  if (!userId) return new Response("Unauthorized", { status: 401 });\n  return Response.json(await db.profile.findByUserId(userId));\n}',
    },
    {
      id: 'auth.user-id-from-body',
      name: 'user_id Accepted from Request Body',
      description: 'user_id or ownerId is read from the client-controlled request body — enables IDOR/BOLA attacks',
      engine: 'static',
      category: 'Authentication',
      severity: 'high',
      confidence: 'medium',
      owasp2025: ['A01 Broken Access Control'],
      cwe: ['CWE-639'],
      asvs: ['ASVS 4.2.1'],
      wstg: ['WSTG-ATHZ-04'],
      tags: ['idor', 'bola', 'auth', 'access-control'],
      enabledByDefault: true,
      safeForCI: true,
      requiresRuntime: false,
      requiresAuth: false,
      remediation: 'Never trust user_id from the client. Extract it from the authenticated session server-side.',
      insecureExample: 'const { userId } = await req.json(); // attacker sends any userId\nawait db.posts.findByUserId(userId);',
      saferExample: 'const { userId } = await auth(); // from verified session token\nawait db.posts.findByUserId(userId);',
    },
    {
      id: 'auth.supabase-service-role-in-client',
      name: 'Supabase Service Role Key in Client File',
      description: 'Supabase service role key referenced in a client-side file — this key bypasses Row Level Security completely',
      engine: 'static',
      category: 'Authentication',
      severity: 'critical',
      confidence: 'high',
      owasp2025: ['A04 Cryptographic Failures', 'A01 Broken Access Control'],
      cwe: ['CWE-312', 'CWE-284'],
      asvs: ['ASVS 2.6.2'],
      wstg: ['WSTG-CRYP-04'],
      tags: ['supabase', 'service-role', 'rls', 'critical'],
      enabledByDefault: true,
      safeForCI: true,
      requiresRuntime: false,
      requiresAuth: false,
      remediation: 'Never use the service role key on the client. Use the anon key for client-side, service role only in server-side code.',
      insecureExample: '"use client";\nconst supabase = createClient(url, process.env.SUPABASE_SERVICE_ROLE_KEY!); // bypasses RLS',
      saferExample: '"use client";\nconst supabase = createClient(url, process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!); // anon key only on client',
    },
    {
      id: 'auth.stripe-secret-in-client',
      name: 'Stripe Secret Key Referenced in Client File',
      description: 'STRIPE_SECRET or stripe secret key pattern found in a client-side file, exposing it to browser users',
      engine: 'static',
      category: 'Authentication',
      severity: 'critical',
      confidence: 'medium',
      owasp2025: ['A04 Cryptographic Failures'],
      cwe: ['CWE-312'],
      asvs: ['ASVS 2.6.2'],
      wstg: ['WSTG-CRYP-04'],
      tags: ['stripe', 'secret', 'client'],
      enabledByDefault: true,
      safeForCI: true,
      requiresRuntime: false,
      requiresAuth: false,
      remediation: 'Only use NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY on the client. Keep STRIPE_SECRET_KEY server-side only.',
      insecureExample: '"use client";\nconst stripe = new Stripe(process.env.STRIPE_SECRET_KEY!); // secret exposed to browser',
      saferExample: '// Server component or API route only:\nconst stripe = new Stripe(process.env.STRIPE_SECRET_KEY!);\n// Client only uses publishable key',
    },
  ],
};
