import type { RulePack } from '@cybermat/shared';

export const configPack: RulePack = {
  id: 'config',
  name: 'Configuration & Misconfiguration',
  description: 'Detects insecure CORS, missing security headers, exposed config files, and framework misconfigurations',
  rules: [
    {
      id: 'config.exposed-env-file',
      name: 'Environment File Potentially Committed',
      description: '.env file present in scanned directory with content — if committed to version control, all secrets are exposed',
      engine: 'config',
      category: 'Configuration',
      severity: 'high',
      confidence: 'medium',
      owasp2025: ['A02 Security Misconfiguration', 'A04 Cryptographic Failures'],
      cwe: ['CWE-312'],
      asvs: ['ASVS 2.6.2'],
      wstg: ['WSTG-CONF-07'],
      tags: ['env-file', 'secrets', 'config'],
      enabledByDefault: true,
      safeForCI: true,
      requiresRuntime: false,
      requiresAuth: false,
      falsePositiveNotes: 'Add "# FAKE" or "# TEST" comment to skip if the file contains only example values.',
      remediation: 'Add .env to .gitignore. Use .env.example for documentation. Rotate any real secrets already committed.',
      insecureExample: '# .env committed to git\nDATABASE_URL=postgresql://user:realpassword@host/db',
      saferExample: '# .env in .gitignore\n# .env.example committed with placeholder values:\nDATABASE_URL=postgresql://user:password@localhost/mydb',
    },
    {
      id: 'config.cors-wildcard-origin',
      name: 'Permissive CORS Wildcard Origin',
      description: 'CORS wildcard origin (*) allows any website to make cross-origin requests to your API',
      engine: 'config',
      category: 'Configuration',
      severity: 'medium',
      confidence: 'high',
      owasp2025: ['A02 Security Misconfiguration'],
      cwe: ['CWE-942'],
      asvs: ['ASVS 14.4.1'],
      wstg: ['WSTG-CONF-10'],
      tags: ['cors', 'config', 'headers'],
      enabledByDefault: true,
      safeForCI: true,
      requiresRuntime: false,
      requiresAuth: false,
      falsePositiveNotes: 'Public APIs intentionally using CORS * may suppress this. Severity escalates to critical when combined with credentials:true.',
      remediation: 'Restrict CORS to specific allowed origins. Never use credentials:true with origin:*.',
      insecureExample: "res.setHeader('Access-Control-Allow-Origin', '*');",
      saferExample: "const allowed = ['https://app.example.com'];\nres.setHeader('Access-Control-Allow-Origin', allowed.includes(req.headers.origin) ? req.headers.origin : '');",
    },
    {
      id: 'config.next-missing-security-headers',
      name: 'Missing Security Headers in next.config.js',
      description: 'next.config.js has no headers() configuration — CSP, HSTS, X-Frame-Options, and other security headers are not set',
      engine: 'config',
      category: 'Configuration',
      severity: 'medium',
      confidence: 'high',
      owasp2025: ['A02 Security Misconfiguration'],
      cwe: ['CWE-693'],
      asvs: ['ASVS 14.4.3', 'ASVS 14.4.4'],
      wstg: ['WSTG-CONF-10'],
      tags: ['nextjs', 'headers', 'csp', 'hsts'],
      enabledByDefault: true,
      safeForCI: true,
      requiresRuntime: false,
      requiresAuth: false,
      remediation: 'Add a headers() function in next.config.js to set Content-Security-Policy, HSTS, X-Frame-Options, X-Content-Type-Options.',
      insecureExample: '// next.config.js — no headers() function',
      saferExample: "async headers() {\n  return [{ source: '/(.*)', headers: [\n    { key: 'X-Frame-Options', value: 'DENY' },\n    { key: 'X-Content-Type-Options', value: 'nosniff' },\n    { key: 'Strict-Transport-Security', value: 'max-age=63072000' },\n    { key: 'Content-Security-Policy', value: \"default-src 'self'\" },\n  ]}];\n}",
    },
    {
      id: 'config.next-source-maps',
      name: 'Production Source Maps Enabled',
      description: 'productionBrowserSourceMaps:true exposes original application code to anyone viewing the site in DevTools',
      engine: 'config',
      category: 'Configuration',
      severity: 'medium',
      confidence: 'high',
      owasp2025: ['A02 Security Misconfiguration'],
      cwe: ['CWE-540'],
      asvs: ['ASVS 14.3.1'],
      wstg: ['WSTG-CONF-01'],
      tags: ['nextjs', 'source-maps', 'config'],
      enabledByDefault: true,
      safeForCI: true,
      requiresRuntime: false,
      requiresAuth: false,
      remediation: 'Remove productionBrowserSourceMaps:true from next.config.js unless intentionally serving source maps for error tracking.',
      insecureExample: '// next.config.js\nproductionBrowserSourceMaps: true,',
      saferExample: '// Remove the flag entirely (defaults to false)\n// Use Sentry or similar for server-side source map uploads instead',
    },
    {
      id: 'config.firebase-permissive-rules',
      name: 'Firebase Security Rules Allow Public Access',
      description: 'Firebase rules contain "allow read/write: if true" — the database is publicly accessible to anyone without authentication',
      engine: 'config',
      category: 'Configuration',
      severity: 'critical',
      confidence: 'high',
      owasp2025: ['A01 Broken Access Control', 'A02 Security Misconfiguration'],
      cwe: ['CWE-284'],
      asvs: ['ASVS 4.1.1'],
      wstg: ['WSTG-ATHZ-01'],
      tags: ['firebase', 'security-rules', 'critical'],
      enabledByDefault: true,
      safeForCI: true,
      requiresRuntime: false,
      requiresAuth: false,
      remediation: 'Require authentication in Firebase rules: allow read: if request.auth != null. Apply field-level validation.',
      insecureExample: 'match /users/{doc} {\n  allow read, write: if true; // anyone can access\n}',
      saferExample: 'match /users/{userId} {\n  allow read, write: if request.auth != null && request.auth.uid == userId;\n}',
    },
    {
      id: 'config.supabase-missing-rls',
      name: 'Supabase Detected Without Row Level Security Policies',
      description: 'Supabase is used but no SQL migrations or RLS policies were found — any authenticated user can read all table rows',
      engine: 'config',
      category: 'Configuration',
      severity: 'high',
      confidence: 'low',
      owasp2025: ['A01 Broken Access Control'],
      cwe: ['CWE-284'],
      asvs: ['ASVS 4.2.1'],
      wstg: ['WSTG-ATHZ-01'],
      tags: ['supabase', 'rls', 'access-control'],
      enabledByDefault: true,
      safeForCI: true,
      requiresRuntime: false,
      requiresAuth: false,
      falsePositiveNotes: 'Low confidence — RLS may be configured in a location not scanned (e.g., Supabase dashboard). Verify manually.',
      remediation: 'Enable RLS on every Supabase table: ALTER TABLE users ENABLE ROW LEVEL SECURITY. Define per-user access policies.',
      insecureExample: '-- No RLS enabled, any authenticated user reads all rows\nSELECT * FROM users;',
      saferExample: 'ALTER TABLE users ENABLE ROW LEVEL SECURITY;\nCREATE POLICY "Users view own data" ON users FOR SELECT\n  USING (auth.uid() = id);',
    },
  ],
};
