import type { RulePack } from '@cybermat/shared';

export const cryptoPack: RulePack = {
  id: 'crypto',
  name: 'Cryptography & Session Security',
  description: 'Detects insecure token storage in browser storage and misconfigured cookie security flags',
  rules: [
    {
      id: 'crypto.token-in-localstorage',
      name: 'Auth Token Stored in localStorage',
      description: 'Auth token written to localStorage — readable by any JavaScript on the page, including XSS payloads',
      engine: 'static',
      category: 'Cryptography',
      severity: 'high',
      confidence: 'high',
      owasp2025: ['A04 Cryptographic Failures', 'A07 Authentication Failures'],
      cwe: ['CWE-922'],
      asvs: ['ASVS 3.4.2'],
      wstg: ['WSTG-SESS-09'],
      tags: ['localstorage', 'token', 'xss', 'session'],
      enabledByDefault: true,
      safeForCI: true,
      requiresRuntime: false,
      requiresAuth: false,
      remediation: 'Use HttpOnly cookies for session tokens instead of localStorage. If using localStorage, ensure XSS is fully mitigated.',
      insecureExample: "localStorage.setItem('token', accessToken); // readable by XSS",
      saferExample: '// Server sets HttpOnly cookie:\nres.cookie("session", token, { httpOnly: true, secure: true, sameSite: "lax" });\n// Client never touches the token directly',
    },
    {
      id: 'crypto.token-in-sessionstorage',
      name: 'Auth Token Stored in sessionStorage',
      description: 'Auth token written to sessionStorage — like localStorage, it is accessible to any JavaScript including XSS payloads',
      engine: 'static',
      category: 'Cryptography',
      severity: 'medium',
      confidence: 'high',
      owasp2025: ['A04 Cryptographic Failures'],
      cwe: ['CWE-922'],
      asvs: ['ASVS 3.4.2'],
      wstg: ['WSTG-SESS-09'],
      tags: ['sessionstorage', 'token', 'xss', 'session'],
      enabledByDefault: true,
      safeForCI: true,
      requiresRuntime: false,
      requiresAuth: false,
      remediation: 'Use HttpOnly cookies for session tokens instead of sessionStorage.',
      insecureExample: "sessionStorage.setItem('jwt', token);",
      saferExample: '// Use HttpOnly cookies — the browser sends them automatically\n// and they cannot be read by JavaScript',
    },
    {
      id: 'crypto.insecure-cookie',
      name: 'Cookie Missing Security Flags',
      description: 'Cookie is set without HttpOnly, Secure, or SameSite flags — vulnerable to XSS token theft, network interception, or CSRF',
      engine: 'static',
      category: 'Cryptography',
      severity: 'medium',
      confidence: 'low',
      owasp2025: ['A04 Cryptographic Failures', 'A07 Authentication Failures'],
      cwe: ['CWE-614', 'CWE-1004'],
      asvs: ['ASVS 3.4.1', 'ASVS 3.4.3', 'ASVS 3.4.5'],
      wstg: ['WSTG-SESS-02'],
      tags: ['cookie', 'session', 'csrf', 'xss'],
      enabledByDefault: true,
      safeForCI: true,
      requiresRuntime: false,
      requiresAuth: false,
      falsePositiveNotes: 'Low confidence — flags may be set on adjacent lines not captured. Review full cookie-setting context.',
      remediation: 'Set cookies with HttpOnly, Secure, and SameSite=Lax (or Strict) flags.',
      insecureExample: "res.cookie('session', token); // no flags",
      saferExample: "res.cookie('session', token, {\n  httpOnly: true,\n  secure: true,\n  sameSite: 'lax',\n  maxAge: 3600000,\n});",
    },
  ],
};
