import type { RulePack } from '@cybermat/shared';

export const injectionPack: RulePack = {
  id: 'injection',
  name: 'Injection & XSS',
  description: 'Detects XSS sinks, SQL injection, command execution, and other code injection vulnerabilities in TypeScript/JavaScript',
  rules: [
    {
      id: 'injection.dangerous-set-inner-html',
      name: 'dangerouslySetInnerHTML Usage',
      description: 'React dangerouslySetInnerHTML bypasses React\'s built-in XSS protection and renders raw HTML directly into the DOM',
      engine: 'static',
      category: 'Injection',
      severity: 'high',
      confidence: 'medium',
      owasp2025: ['A05 Injection'],
      cwe: ['CWE-79'],
      asvs: ['ASVS 5.2.1'],
      wstg: ['WSTG-INPV-01'],
      tags: ['xss', 'react', 'dom'],
      enabledByDefault: true,
      safeForCI: true,
      requiresRuntime: false,
      requiresAuth: false,
      falsePositiveNotes: 'May fire on sanitized HTML. Check if DOMPurify or a similar sanitizer is applied before render.',
      remediation: 'Avoid dangerouslySetInnerHTML. Use DOMPurify to sanitize HTML if raw rendering is required.',
      insecureExample: '<div dangerouslySetInnerHTML={{ __html: userInput }} />',
      saferExample: 'import DOMPurify from "dompurify";\n<div dangerouslySetInnerHTML={{ __html: DOMPurify.sanitize(userInput) }} />',
    },
    {
      id: 'injection.inner-html-assignment',
      name: 'innerHTML / outerHTML / insertAdjacentHTML',
      description: 'Direct DOM innerHTML assignment injects raw HTML without sanitization, enabling XSS if user-controlled input is used',
      engine: 'static',
      category: 'Injection',
      severity: 'high',
      confidence: 'medium',
      owasp2025: ['A05 Injection'],
      cwe: ['CWE-79'],
      asvs: ['ASVS 5.2.1'],
      wstg: ['WSTG-INPV-01'],
      tags: ['xss', 'dom'],
      enabledByDefault: true,
      safeForCI: true,
      requiresRuntime: false,
      requiresAuth: false,
      falsePositiveNotes: 'May fire on static HTML strings that contain no user input. Review whether the value is user-controlled.',
      remediation: 'Use textContent for plain text. Sanitize with DOMPurify before assigning innerHTML.',
      insecureExample: 'element.innerHTML = req.body.comment;',
      saferExample: 'element.textContent = req.body.comment; // for plain text\n// or: element.innerHTML = DOMPurify.sanitize(req.body.comment);',
    },
    {
      id: 'injection.document-write',
      name: 'document.write Usage',
      description: 'document.write renders content directly into the document and can be exploited for XSS; it also blocks page rendering',
      engine: 'static',
      category: 'Injection',
      severity: 'high',
      confidence: 'high',
      owasp2025: ['A05 Injection'],
      cwe: ['CWE-79'],
      asvs: ['ASVS 5.2.1'],
      wstg: ['WSTG-INPV-01'],
      tags: ['xss', 'dom'],
      enabledByDefault: true,
      safeForCI: true,
      requiresRuntime: false,
      requiresAuth: false,
      remediation: 'Replace with safe DOM manipulation APIs: createElement, appendChild, textContent.',
      insecureExample: 'document.write("<script>alert(1)</script>");',
      saferExample: 'const el = document.createElement("p");\nel.textContent = content;\ndocument.body.appendChild(el);',
    },
    {
      id: 'injection.eval-usage',
      name: 'eval() / new Function() Usage',
      description: 'eval() and new Function() execute arbitrary code strings, enabling code injection and XSS if user input reaches them',
      engine: 'static',
      category: 'Injection',
      severity: 'high',
      confidence: 'high',
      owasp2025: ['A05 Injection'],
      cwe: ['CWE-78', 'CWE-79'],
      asvs: ['ASVS 5.2.4'],
      wstg: ['WSTG-INPV-11'],
      tags: ['code-injection', 'eval'],
      enabledByDefault: true,
      safeForCI: true,
      requiresRuntime: false,
      requiresAuth: false,
      falsePositiveNotes: 'Can fire on legitimate uses like JSON.parse alternatives or transpiler output. Review callsite.',
      remediation: 'Never use eval() or new Function() with untrusted input. Redesign logic using safe alternatives.',
      insecureExample: 'eval(req.body.expression); // remote code execution',
      saferExample: '// Use a safe expression evaluator library, or redesign\n// to avoid dynamic code execution entirely',
    },
    {
      id: 'injection.settimeout-string',
      name: 'setTimeout / setInterval with String Argument',
      description: 'String arguments to setTimeout/setInterval are passed to eval() internally, enabling code injection',
      engine: 'static',
      category: 'Injection',
      severity: 'medium',
      confidence: 'high',
      owasp2025: ['A05 Injection'],
      cwe: ['CWE-79'],
      tags: ['eval', 'dom'],
      enabledByDefault: true,
      safeForCI: true,
      requiresRuntime: false,
      requiresAuth: false,
      remediation: 'Pass a function reference instead of a string: setTimeout(() => fn(), delay).',
      insecureExample: 'setTimeout("doSomething()", 1000); // string is eval\'d',
      saferExample: 'setTimeout(() => doSomething(), 1000);',
    },
    {
      id: 'injection.prisma-query-raw-unsafe',
      name: 'Prisma.$queryRawUnsafe Usage',
      description: '$queryRawUnsafe and $executeRawUnsafe bypass Prisma\'s parameterization, enabling SQL injection',
      engine: 'static',
      category: 'Injection',
      severity: 'critical',
      confidence: 'high',
      owasp2025: ['A05 Injection'],
      cwe: ['CWE-89'],
      asvs: ['ASVS 5.3.4'],
      wstg: ['WSTG-INPV-05'],
      tags: ['sql-injection', 'prisma', 'database'],
      enabledByDefault: true,
      safeForCI: true,
      requiresRuntime: false,
      requiresAuth: false,
      remediation: 'Use Prisma.$queryRaw with tagged template literals, or use parameterized Prisma client methods.',
      insecureExample: 'await prisma.$queryRawUnsafe(`SELECT * FROM users WHERE id = ${userId}`);',
      saferExample: 'await prisma.$queryRaw`SELECT * FROM users WHERE id = ${userId}`;',
    },
    {
      id: 'injection.sql-string-concat',
      name: 'SQL String Concatenation',
      description: 'SQL query built by concatenating user-controlled variables enables SQL injection attacks',
      engine: 'static',
      category: 'Injection',
      severity: 'high',
      confidence: 'medium',
      owasp2025: ['A05 Injection'],
      cwe: ['CWE-89'],
      asvs: ['ASVS 5.3.4'],
      wstg: ['WSTG-INPV-05'],
      tags: ['sql-injection', 'database'],
      enabledByDefault: true,
      safeForCI: true,
      requiresRuntime: false,
      requiresAuth: false,
      falsePositiveNotes: 'May fire on SQL building with known-safe constant values. Review whether concatenated variables are user-controlled.',
      remediation: 'Use parameterized queries or an ORM. Never concatenate user input into SQL strings.',
      insecureExample: "const q = `SELECT * FROM users WHERE name = '${req.query.name}'`;",
      saferExample: 'const q = "SELECT * FROM users WHERE name = ?";\ndb.query(q, [req.query.name]);',
    },
    {
      id: 'injection.child-process-exec',
      name: 'child_process.exec / execSync',
      description: 'exec() and execSync() invoke a shell command, enabling command injection if user input reaches the argument',
      engine: 'static',
      category: 'Injection',
      severity: 'critical',
      confidence: 'medium',
      owasp2025: ['A05 Injection'],
      cwe: ['CWE-78'],
      asvs: ['ASVS 5.3.8'],
      wstg: ['WSTG-INPV-12'],
      tags: ['command-injection', 'rce', 'shell'],
      enabledByDefault: true,
      safeForCI: true,
      requiresRuntime: false,
      requiresAuth: false,
      falsePositiveNotes: 'Fires in tool scripts and build utilities where exec is called with static, trusted arguments. Review whether the argument contains user input.',
      remediation: 'Use execFile() with an array of arguments instead. Never pass user input to exec().',
      insecureExample: 'exec(`convert ${req.body.file} output.png`); // command injection',
      saferExample: "execFile('convert', [req.body.file, 'output.png']); // args array, no shell",
    },
  ],
};
