import type { Severity } from '@cybermat/shared';

export interface MultiLangDetector {
  id: string;
  name: string;
  /** ScannedFile.language values this detector targets */
  languages: string[];
  /** Optional: also restrict to specific fileKind values */
  fileKinds?: string[];
  /** The pattern to run against each line */
  pattern: RegExp;
  severity: Severity;
  confidence: 'high' | 'medium' | 'low';
  owasp: string[];
  cwe: string[];
  impact: string;
  recommendation: string;
  tags: string[];
}

export const MULTILANG_DETECTORS: MultiLangDetector[] = [

  // ─── Docker ────────────────────────────────────────────────────────────────

  {
    id: 'docker.curl-pipe-sh',
    name: 'Curl/Wget piped to shell in Dockerfile',
    languages: ['dockerfile'],
    pattern: /(?:curl|wget)\s[^\n]*\|\s*(?:sh|bash|ash|dash|zsh)/i,
    severity: 'high',
    confidence: 'high',
    owasp: ['A08 Software or Data Integrity Failures'],
    cwe: ['CWE-494'],
    impact: 'Remote code execution via untrusted script download and execution.',
    recommendation: 'Download the script, verify its checksum, then execute. Never pipe curl directly to a shell.',
    tags: ['docker', 'rce', 'supply-chain'],
  },
  {
    id: 'docker.add-remote-url',
    name: 'Dockerfile ADD with remote URL',
    languages: ['dockerfile'],
    pattern: /^\s*ADD\s+https?:\/\//i,
    severity: 'medium',
    confidence: 'high',
    owasp: ['A08 Software or Data Integrity Failures'],
    cwe: ['CWE-494'],
    impact: 'ADD fetches remote content at build time with no integrity verification.',
    recommendation: 'Use COPY with pre-downloaded and checksummed files, or RUN curl with --fail and checksum verification.',
    tags: ['docker', 'supply-chain'],
  },
  {
    id: 'docker.secret-in-env',
    name: 'Potential secret in Dockerfile ENV',
    languages: ['dockerfile'],
    pattern: /^\s*ENV\s+\S*(?:SECRET|PASSWORD|PASSWD|TOKEN|API_KEY|APIKEY|PRIVATE_KEY|ACCESS_KEY)\S*\s*[=\s]\s*\S+/i,
    severity: 'high',
    confidence: 'medium',
    owasp: ['A02 Security Misconfiguration'],
    cwe: ['CWE-798'],
    impact: 'Secrets baked into ENV are visible in image layers and `docker inspect` output.',
    recommendation: 'Use Docker BuildKit secrets (--secret), multi-stage builds, or runtime env injection via orchestrator.',
    tags: ['docker', 'secrets', 'hardcoded-credentials'],
  },
  {
    id: 'docker.privileged-container',
    name: 'Privileged container in compose file',
    languages: ['yaml'],
    fileKinds: ['docker'],
    pattern: /^\s*privileged\s*:\s*true/i,
    severity: 'high',
    confidence: 'high',
    owasp: ['A01 Broken Access Control'],
    cwe: ['CWE-250'],
    impact: 'Privileged containers have full host access, negating container isolation.',
    recommendation: 'Remove privileged: true. Use specific Linux capabilities instead (cap_add).',
    tags: ['docker', 'privilege-escalation', 'container-escape'],
  },
  {
    id: 'docker.docker-sock-mount',
    name: 'Docker socket mounted in container',
    languages: ['yaml', 'dockerfile'],
    fileKinds: ['docker'],
    pattern: /\/var\/run\/docker\.sock/,
    severity: 'high',
    confidence: 'high',
    owasp: ['A01 Broken Access Control'],
    cwe: ['CWE-269'],
    impact: 'Mounting the Docker socket gives the container full control over the Docker daemon and host.',
    recommendation: 'Avoid mounting docker.sock. Use Docker-in-Docker alternatives or restrict access with authorization plugins.',
    tags: ['docker', 'privilege-escalation', 'container-escape'],
  },
  {
    id: 'docker.host-network',
    name: 'Host network mode in compose file',
    languages: ['yaml'],
    fileKinds: ['docker'],
    pattern: /network_mode\s*:\s*["']?host["']?/i,
    severity: 'medium',
    confidence: 'high',
    owasp: ['A02 Security Misconfiguration'],
    cwe: ['CWE-668'],
    impact: 'Host network mode removes network isolation between the container and host.',
    recommendation: 'Use bridge or custom networks. Only use host network mode when explicitly required and justified.',
    tags: ['docker', 'network-isolation'],
  },

  // ─── Shell scripts ─────────────────────────────────────────────────────────

  {
    id: 'shell.curl-pipe-sh',
    name: 'Curl/Wget piped to shell',
    languages: ['shell'],
    pattern: /(?:curl|wget)\s[^\n]*\|\s*(?:sh|bash|ash|dash|zsh)/i,
    severity: 'high',
    confidence: 'high',
    owasp: ['A08 Software or Data Integrity Failures'],
    cwe: ['CWE-494'],
    impact: 'Downloads and immediately executes remote code with no integrity check.',
    recommendation: 'Download separately, verify checksum, then execute. Or pin the version and hash.',
    tags: ['shell', 'rce', 'supply-chain'],
  },
  {
    id: 'shell.eval-usage',
    name: 'eval() in shell script',
    languages: ['shell'],
    pattern: /(?:^|;|\s)eval\s/,
    severity: 'medium',
    confidence: 'medium',
    owasp: ['A03 Software Supply Chain Failures'],
    cwe: ['CWE-78'],
    impact: 'eval executes arbitrary strings as code. If the input is user-controlled or external, this enables RCE.',
    recommendation: 'Avoid eval. Use arrays or named functions to handle dynamic behavior safely.',
    tags: ['shell', 'code-injection'],
  },
  {
    id: 'shell.insecure-chmod',
    name: 'chmod 777 in shell script',
    languages: ['shell'],
    pattern: /chmod\s+(?:[ugo+]+=?)*777\b|chmod\s+a\+rwx\b/,
    severity: 'medium',
    confidence: 'medium',
    owasp: ['A01 Broken Access Control'],
    cwe: ['CWE-732'],
    impact: 'World-writable files allow any user on the system to read, write, or execute.',
    recommendation: 'Use the least-permissive mode needed. Prefer 750 for executables, 640 for files.',
    tags: ['shell', 'permissions'],
  },
  {
    id: 'shell.tls-disabled-curl',
    name: 'TLS verification disabled in curl',
    languages: ['shell'],
    pattern: /\bcurl\b[^\n]*\s(?:-[kK]\b|--insecure\b)/,
    severity: 'medium',
    confidence: 'high',
    owasp: ['A02 Security Misconfiguration'],
    cwe: ['CWE-295'],
    impact: 'Disabling TLS certificate verification allows MITM attacks on the connection.',
    recommendation: 'Remove -k/--insecure. Fix the underlying certificate issue instead.',
    tags: ['shell', 'tls', 'mitm'],
  },
  {
    id: 'shell.tls-disabled-wget',
    name: 'TLS verification disabled in wget',
    languages: ['shell'],
    pattern: /wget\s[^\n]*--no-check-certificate\b/,
    severity: 'medium',
    confidence: 'high',
    owasp: ['A02 Security Misconfiguration'],
    cwe: ['CWE-295'],
    impact: 'Disabling TLS certificate verification allows MITM attacks on the connection.',
    recommendation: 'Remove --no-check-certificate. Fix the underlying certificate issue instead.',
    tags: ['shell', 'tls', 'mitm'],
  },

  // ─── Terraform / HCL ──────────────────────────────────────────────────────

  {
    id: 'terraform.public-s3',
    name: 'S3 bucket with public read ACL',
    languages: ['terraform', 'hcl'],
    pattern: /acl\s*=\s*["']public-read(?:-write)?["']/i,
    severity: 'high',
    confidence: 'high',
    owasp: ['A01 Broken Access Control'],
    cwe: ['CWE-284'],
    impact: 'Public-read or public-read-write S3 ACLs expose bucket contents to the internet.',
    recommendation: 'Use private ACL and bucket policies. Enable S3 Block Public Access.',
    tags: ['terraform', 'aws', 's3', 'data-exposure'],
  },
  {
    id: 'terraform.ssh-open-world',
    name: 'SSH port open to the world in security group',
    languages: ['terraform', 'hcl'],
    pattern: /(?:from_port|to_port)\s*=\s*22[\s\S]{0,200}?(?:cidr_blocks|ipv6_cidr_blocks)\s*=\s*\[?\s*["'](?:0\.0\.0\.0\/0|::\/0)["']/,
    severity: 'high',
    confidence: 'medium',
    owasp: ['A02 Security Misconfiguration'],
    cwe: ['CWE-284'],
    impact: 'SSH open to 0.0.0.0/0 exposes the host to brute-force and exploitation from the internet.',
    recommendation: 'Restrict SSH to specific IP ranges or use AWS Systems Manager Session Manager instead.',
    tags: ['terraform', 'aws', 'network', 'ssh'],
  },
  {
    id: 'terraform.rdp-open-world',
    name: 'RDP port open to the world in security group',
    languages: ['terraform', 'hcl'],
    pattern: /(?:from_port|to_port)\s*=\s*3389[\s\S]{0,200}?(?:cidr_blocks|ipv6_cidr_blocks)\s*=\s*\[?\s*["'](?:0\.0\.0\.0\/0|::\/0)["']/,
    severity: 'high',
    confidence: 'medium',
    owasp: ['A02 Security Misconfiguration'],
    cwe: ['CWE-284'],
    impact: 'RDP open to 0.0.0.0/0 exposes Windows hosts to credential attacks from the internet.',
    recommendation: 'Restrict RDP to specific IP ranges or use a VPN / bastion host.',
    tags: ['terraform', 'aws', 'network', 'rdp'],
  },

  // ─── Kubernetes ────────────────────────────────────────────────────────────

  {
    id: 'k8s.privileged-container',
    name: 'Privileged Kubernetes container',
    languages: ['yaml'],
    pattern: /privileged\s*:\s*true/i,
    severity: 'critical',
    confidence: 'high',
    owasp: ['A01 Broken Access Control'],
    cwe: ['CWE-250'],
    impact: 'Privileged pods have unrestricted access to the host kernel and can escape container isolation.',
    recommendation: 'Remove privileged: true. Use specific capabilities via securityContext.capabilities.add.',
    tags: ['kubernetes', 'privilege-escalation', 'container-escape'],
  },
  {
    id: 'k8s.host-network',
    name: 'Kubernetes pod with hostNetwork',
    languages: ['yaml'],
    pattern: /hostNetwork\s*:\s*true/i,
    severity: 'high',
    confidence: 'high',
    owasp: ['A02 Security Misconfiguration'],
    cwe: ['CWE-668'],
    impact: 'hostNetwork: true removes network namespace isolation between pod and host.',
    recommendation: 'Remove hostNetwork: true unless strictly necessary for infrastructure components.',
    tags: ['kubernetes', 'network-isolation'],
  },
  {
    id: 'k8s.host-pid',
    name: 'Kubernetes pod with hostPID',
    languages: ['yaml'],
    pattern: /hostPID\s*:\s*true/i,
    severity: 'high',
    confidence: 'high',
    owasp: ['A01 Broken Access Control'],
    cwe: ['CWE-668'],
    impact: 'hostPID: true allows the container to see and signal all host processes.',
    recommendation: 'Remove hostPID: true unless strictly necessary.',
    tags: ['kubernetes', 'privilege-escalation'],
  },
  {
    id: 'k8s.run-as-root',
    name: 'Kubernetes container running as root (UID 0)',
    languages: ['yaml'],
    pattern: /runAsUser\s*:\s*0\b/,
    severity: 'high',
    confidence: 'high',
    owasp: ['A02 Security Misconfiguration'],
    cwe: ['CWE-250'],
    impact: 'Running as UID 0 inside a container increases the blast radius if the container is compromised.',
    recommendation: 'Set runAsNonRoot: true and runAsUser to a non-zero UID.',
    tags: ['kubernetes', 'least-privilege'],
  },
  {
    id: 'k8s.allow-privilege-escalation',
    name: 'Kubernetes allowPrivilegeEscalation: true',
    languages: ['yaml'],
    pattern: /allowPrivilegeEscalation\s*:\s*true/i,
    severity: 'high',
    confidence: 'high',
    owasp: ['A01 Broken Access Control'],
    cwe: ['CWE-250'],
    impact: 'Allows processes to gain more privileges than their parent, enabling privilege escalation attacks.',
    recommendation: 'Set allowPrivilegeEscalation: false in securityContext.',
    tags: ['kubernetes', 'privilege-escalation'],
  },

  // ─── Python ────────────────────────────────────────────────────────────────

  {
    id: 'python.eval-exec',
    name: 'Python eval() or exec()',
    languages: ['python'],
    pattern: /(?<![.\w])(?:eval|exec)\s*\(/,
    severity: 'medium',
    confidence: 'medium',
    owasp: ['A03 Software Supply Chain Failures'],
    cwe: ['CWE-78', 'CWE-95'],
    impact: 'eval/exec execute arbitrary Python code. If input is user-controlled this enables RCE.',
    recommendation: 'Avoid eval/exec. Use literal_eval from ast for safe expression parsing.',
    tags: ['python', 'code-injection', 'rce'],
  },
  {
    id: 'python.subprocess-shell',
    name: 'Python subprocess with shell=True',
    languages: ['python'],
    pattern: /subprocess\.\w+\s*\([^)]*shell\s*=\s*True/,
    severity: 'high',
    confidence: 'high',
    owasp: ['A03 Software Supply Chain Failures'],
    cwe: ['CWE-78'],
    impact: 'shell=True passes the command through the shell interpreter, enabling command injection.',
    recommendation: 'Use shell=False (default) and pass command as a list of arguments.',
    tags: ['python', 'command-injection', 'rce'],
  },
  {
    id: 'python.pickle-loads',
    name: 'Python pickle.loads() / pickle.load()',
    languages: ['python'],
    pattern: /(?<![.\w])pickle\.loads?\s*\(/,
    severity: 'high',
    confidence: 'high',
    owasp: ['A08 Software or Data Integrity Failures'],
    cwe: ['CWE-502'],
    impact: 'Deserializing untrusted pickle data can execute arbitrary Python code.',
    recommendation: 'Never deserialize pickle data from untrusted sources. Use JSON or a safe serialization format.',
    tags: ['python', 'deserialization', 'rce'],
  },
  {
    id: 'python.yaml-unsafe-load',
    name: 'Python yaml.load() without SafeLoader',
    languages: ['python'],
    pattern: /yaml\.load\s*\([^)]*(?!\bLoader\s*=\s*yaml\.(?:Safe|Base)Loader)/,
    severity: 'medium',
    confidence: 'medium',
    owasp: ['A08 Software or Data Integrity Failures'],
    cwe: ['CWE-502'],
    impact: 'yaml.load() with the default loader can deserialize arbitrary Python objects.',
    recommendation: 'Use yaml.safe_load() or yaml.load(data, Loader=yaml.SafeLoader) instead.',
    tags: ['python', 'deserialization'],
  },

  // ─── PHP ───────────────────────────────────────────────────────────────────

  {
    id: 'php.eval',
    name: 'PHP eval()',
    languages: ['php'],
    pattern: /(?<![.\w])eval\s*\(/,
    severity: 'high',
    confidence: 'medium',
    owasp: ['A03 Software Supply Chain Failures'],
    cwe: ['CWE-95'],
    impact: 'eval() executes arbitrary PHP code. Any user-controlled input reaching eval() enables RCE.',
    recommendation: 'Remove eval(). Refactor to use safe alternatives without code generation.',
    tags: ['php', 'code-injection', 'rce'],
  },
  {
    id: 'php.shell-exec',
    name: 'PHP shell execution functions',
    languages: ['php'],
    pattern: /(?<![.\w])(?:shell_exec|passthru|system|exec|popen|proc_open)\s*\(/,
    severity: 'high',
    confidence: 'medium',
    owasp: ['A03 Software Supply Chain Failures'],
    cwe: ['CWE-78'],
    impact: 'Shell execution functions can enable command injection if input is not sanitized.',
    recommendation: 'Avoid shell execution functions. If necessary, use escapeshellarg() and whitelist allowed commands.',
    tags: ['php', 'command-injection', 'rce'],
  },
  {
    id: 'php.unserialize',
    name: 'PHP unserialize()',
    languages: ['php'],
    pattern: /(?<![.\w])unserialize\s*\(/,
    severity: 'medium',
    confidence: 'medium',
    owasp: ['A08 Software or Data Integrity Failures'],
    cwe: ['CWE-502'],
    impact: 'Deserializing untrusted data with unserialize() can trigger object injection vulnerabilities.',
    recommendation: 'Use JSON for serialization. If PHP serialization is required, use a signed HMAC to validate integrity.',
    tags: ['php', 'deserialization'],
  },

  // ─── CI/CD ─────────────────────────────────────────────────────────────────

  {
    id: 'cicd.curl-pipe-bash',
    name: 'Curl/Wget piped to shell in CI pipeline',
    languages: ['yaml'],
    fileKinds: ['ci_cd'],
    pattern: /(?:curl|wget)\s[^\n]*\|\s*(?:sh|bash|ash|dash|zsh)/i,
    severity: 'high',
    confidence: 'high',
    owasp: ['A08 Software or Data Integrity Failures'],
    cwe: ['CWE-494'],
    impact: 'Downloading and executing remote scripts in CI pipelines enables supply-chain attacks.',
    recommendation: 'Pin script versions with SHA checksum verification, or use verified actions/steps.',
    tags: ['ci-cd', 'supply-chain', 'rce'],
  },
  {
    id: 'cicd.pull-request-target-unsafe',
    name: 'Unsafe pull_request_target checkout in GitHub Actions',
    languages: ['yaml'],
    fileKinds: ['ci_cd'],
    pattern: /pull_request_target[\s\S]{0,300}?github\.event\.pull_request\.head/,
    severity: 'high',
    confidence: 'medium',
    owasp: ['A01 Broken Access Control'],
    cwe: ['CWE-284'],
    impact: 'Checking out untrusted PR head code in pull_request_target context grants it access to repository secrets.',
    recommendation: 'Never check out PR head code in pull_request_target workflows that have access to secrets.',
    tags: ['ci-cd', 'github-actions', 'secrets-exposure'],
  },
];
